New Example Task; Registration Review
* ENH: Move common parsing functionality to data utils

* DOC: Update Doc String to match actual functionality

* ADD: RegistrationReviewDataUnit.py a near copy of MultiContrastSegmentationEvaluationDataUnit

Only difference is if there is no primary segmentation no segmentation node is created

* ADD: Implement RegistrationReviewTask and GUI for managing registration reviews

This should allow for correct selection of data and saving of information

* ENH: ADD Task to CART

* BUG: Update scene parameter to be non-optional in data unit initializers

 # Scene is NOT optional.
# Raises `AttributeError: 'NoneType' object has no attribute 'GetSubjectHierarchyNode'
# Default scene is the global MRML scene, which is always available.

* BUG: Correct prompt resizing method in RegistrationReviewTask

* BUG: Update orientation handling in RegistrationReviewTask to use enum

* ENH: Add registration classification selection to RegistrationReviewTask

* ENH: Add review status display and update mechanism in RegistrationReviewTask

* ENH: Add foreground opacity control and primary volume handling in layout management

* ENH: Update default orientation to AXIAL and add button for TRIO orientation selection

* Fixed changing CART's drop-downs not being reflected in the DataManager

* ENH: Remove outdated OrganLabellingDemo

* ENH: Cleanup unnessicary code from RegistrationReviewDataUnit.py

* ENH: Cleanup unnessicary code from RegistrationReviewTask.py

* ENH: Cleanup unnecessary code from RegistrationReviewTask.py

* ENH: General Cleanup for RegistrationReviewTask.py

---------

Co-authored-by: iejohnson <iejohnson@uiowa.edu>
Co-authored-by: Kalum Ost <kalumost@gmail.com>